version: '3'

services:
  db_postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=rent_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toor
  db_mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper




