server:
  port: ${PORT:8084}
spring:
  application:
    name: authentication-part
  datasource:
    url: jdbc:postgresql://localhost:5432/rent_service
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver
