
server:
  port: ${PORT:8082}
spring:
  application:
    name: photo_module
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
      group-id: myGroup
      auto-offset-reset: earliest
  datasource:
    username: ${MONGO_INITDB_ROOT_USERNAME:admin}
    password: ${MONGO_INITDB_ROOT_PASSWORD:mongo}
    url: jdbc:mongodb://${DB_HOST:localhost}DB_PORT:27017}/${DATABASE:photos}
