server:
  port: ${PORT:8080}
spring:
  application:
    name: rent_module
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rent_service
    hikari:
      maximum-pool-size: 20
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.StringSerializer
      group_id: myGroup
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic


