server:
  port: ${PORT:8084}
spring:
  application:
    name: Authentication
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/rent_service
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver
#  cloud:
#    consul:
#      host: ${CONSUL_HOST:localhost}
#      port: ${CONSUL_PORT:8500}
