server:
  port: ${PORT:8085}
spring:
  application:
    name: gateway-app
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
